# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: tomorrow-night-blue # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl :  # does not include hostname
title:
  br: Ciência e Política
  en: Science and Politics
  es: Ciencia y Política
  de: Wissenschaft und Politik

description:  # this means to ignore newlines until "Language & timezone"
  br: Meu site pessoal de análises e divulgação
  en: My personal site of analysis and dissemination
  es: Mi web personal de análisis y difusión
  de: Meine persönliche Analyse- und Verbreitungsseite


## => Language and Timezone
##############################
lang: br # the language of your site, default as "en"
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : # "person" (default), "organization"
  name      : Gustavo Sabbag
  url       :
  avatar    : # path or url of avatar image (square)
  bio       : Cientista Político
  email     : gussabbag@gmail.com
  facebook  : gustavo.sabbag # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  instagram : sabbaggustavo # "user_name" the last part of your profile url, e.g. https://www.instagram.com/user_name
  twitter   : gusabbag # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : gustavo-sabbag-1950a4169 # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : gustavosabbag # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: gustavosabbag/gustavosabbag.github.io
repository_tree: master


## => Paths
##############################
# Coloquei um path para cada língua. Se for voltar ao original (uma língua somente)
# tenho que procurar todos os documentos com paths[page.lang] e retirar o [page.lang]
paths:
  br:
    root    : /br/ # title link url, "/" (default)
    home    : /br/ # home layout url, "/" (default)
    archive : /br/artigos.html # "/archive.html" (default)
    rss     : /br/ # "/feed.xml" (default)

  en:
    root    : /en/ # title link url, "/" (default)
    home    : /en/ # home layout url, "/" (default)
    archive : /en/articles.html # "/archive.html" (default)
    rss     : /en/feed.xml # "/feed.xml" (default)

  es:
    root    : /es/ # title link url, "/" (default)
    home    : /es/ # home layout url, "/" (default)
    archive : /es/articulos.html # "/archive.html" (default)
    rss     : /es/feed.xml # "/feed.xml" (default)

  de:
    root    : /de/ # title link url, "/" (default)
    home    : /de/ # home layout url, "/" (default)
    archive : /de/Artikel.html # "/archive.html" (default)
    rss     : /de/feed.xml # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /br/page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: addthis # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: ra-5fd2e1f460d01d8e # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: disqus # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: gustavosabbag # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : # LeanCloud App id
    app_key     : # LeanCloud App key
    placeholder : # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: google # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : G-1MCHHPBC44 # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
  - scope:
      path: br
    values:
      lang: br
      base-url: "/br/"
  - scope:
      path: en
    values:
      lang: en
      base-url: "/en/"
  - scope:
      path: es
    values:
      lang: es
      base-url: "/es/"
  - scope:
      path: de
    values:
      lang: de
      base-url: "/de/"

    #Até aqui

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from

# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
staticman_url: https://comentarios-gustavosabbag.herokuapp.com/v2/entry/gustavosabbag/gustavosabbag.github.io/master/comments

# reCaptcha configuration info: the exact same site key and *encrypted* secret that you used in staticman.yml
# I personally don't think the secret needs to be included in the generated site, but the staticman API bridge uses
# it to ensure the site configuration and bridge configuration match (but why not just compare the site key?)
reCaptcha:
  siteKey: 6LekywMaAAAAAO3dUHGVByE7LZdt7D99mQRDfK0O
  secret: I7jNWIZ07CcXLGtNLaW8v+ZHh+Jv6ify4hSyX2Ce5heLAqEe97mA4uDq0XGxU+DQ5RiiTnNpAF/slZGQh4jnzTdJ0ETAiKDgDtwXd9U3qXqOiDiwTeQj5MPjoUDehqpMCnvyf4lMpNla8J54UnCloiMN3PCMmp/YSjMsAGweRp3DSWycc2uSVn2GiWGT+Ko2UvguZHVyK38wsw8lzpcYJB2uMkFBKsblabREcGVA6d4QpogmeSpd7oBnlrIyUmCoKyRPbZqjCia5SJACVR+cEBJ7rorhuGjdsIbup4zSoKOfssvT0zU92NvqsVGYOgVGQ0lhsDncQODhnU9rscyywEYio9hN9zvgqexM0s6b3skIfsKN4d4pMA44YNeBc3nAH8Qitdw5NC1awTMkLtNSWKZY9P52kyOiWi2ETv3vBKJXzstJ2C/KcQFlSloqs2l19AnUELMCOXrBqGDperzSZSRRuRJ8I07hB1x4s3TTjpM2UkeQY594pwDx6145i/UzLEiJlipZ1gFxneJYp6zrLc+CwudrrQ7imAM1OvezXcHABw8QqXyzlN/ER1dImI50FwOKpCgET0HCmy7q0EbMlIDKv0wLbBa4cNJp70Xj0RX4PV8T+DCOr/aX31/HFDnnql0M9+90aum7iW1YoYAIXylosr2x+ExuRSEjp18icME=

remote_theme: kitian616/jekyll-TeXt-theme
